//! Owner: infra. UniFFI exports. Other agents request additions (docs/contracts/build.md).
//!
//! Every `#[uniffi::export]` added here becomes a Swift symbol in `FirstcutCore`
//! (`App/Generated/`, generated by `scripts/build-core.sh`). Keep the surface small and
//! delegate: an agent owns the Rust implementation, infra wires the export and the docs.
//!
//! Conventions:
//! - Exports are grouped by the agent that owns the implementation, with a comment naming them.
//! - Errors that Swift must distinguish are `#[derive(uniffi::Error)]` enums with a
//!   `#[uniffi(flat_error)]` or an explicit `UniffiError` wrapper, never bare `String`.
//! - Types that cross the boundary are declared here as `#[derive(uniffi::Record)]` mirrors of
//!   the Rust types, so the Swift names match `App/Sources/Shared/CoreTypes.swift` exactly.

/// Wave 1 smoke test: proves the Rust core is linked and callable from Swift.
/// Swift side: `FirstcutCore.hello()`.
#[uniffi::export]
pub fn hello() -> String {
    format!(
        "Firstcut core {} (Rust {})",
        env!("CARGO_PKG_VERSION"),
        env!("CARGO_PKG_NAME")
    )
}

/// Crate version of the Rust core, so the app can show which core it is running against.
#[uniffi::export]
pub fn core_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// ─────────────────────────────────────────────────────────────────────────────
// Wave 1 end of infra exports. Next: PhotoMeta / Batch / VisualSig (core-meta,
// core-batch) and Session (core-store), added on request — see the Wave 2 row in
// docs/agents/infra.md.
