// Owner: infra. Proves the Rust core is linked into the app and reachable from Swift.
// Delete nothing here: this is the guard that catches a stale App/Generated or a missing static
// library before it reaches a release.
import Foundation
import Testing

@testable import Firstcut

@Test func coreIsLinkedAndAnswers() {
    #expect(FirstcutCoreBridge.isLinked)
    #expect(FirstcutCoreBridge.greeting.contains("Firstcut core"))
}

@Test func coreVersionIsSemantic() {
    let version = FirstcutCoreBridge.coreVersion
    let parts = version.split(separator: ".")
    #expect(!version.isEmpty)
    #expect((1...3).contains(parts.count))
    #expect(parts.allSatisfy { $0.allSatisfy(\.isNumber) })
}

/// `App/Generated/FirstcutCore.swift` is git-ignored and regenerated by `scripts/build-core.sh`,
/// so "the app talks to the Rust core" is a claim about a file that is not in the repository. This
/// is the guard: it reads the same generated source the app reads, so the inventory in
/// `CoreBridge.swift` fails the moment it drifts.
///
/// It fails in both directions, which is the point. If `ffi.rs` loses an export, the build already
/// broke; if it *gains* one that the inventory does not list, the app is quietly not using it.
@Test func generatedBindingsAreFound() throws {
    let source = try #require(
        FirstcutCoreBridge.generatedBindingsSource,
        "App/Generated/FirstcutCore.swift is not where it should be")
    #expect(source.contains("public func hello()"))
    #expect(source.contains("public func coreVersion()"))
    #expect(source.contains("open class Session: SessionProtocol"))
}

@Test func theSessionInventoryMatchesTheGeneratedBindings() throws {
    let source = try #require(FirstcutCoreBridge.generatedBindingsSource)
    let missing = FirstcutCoreBridge.sessionMembers.filter { !source.contains($0) }
    #expect(missing.isEmpty, "Session members the app expects but the core does not export: \(missing)")
    #expect(FirstcutCoreBridge.hasSessionAPI)
}

@MainActor @Test func finishIsExportedAndTheAppCanRunIt() throws {
    let source = try #require(FirstcutCoreBridge.generatedBindingsSource)
    let missing = FirstcutCoreBridge.finishMembers.filter { !source.contains($0) }
    #expect(missing.isEmpty, "Finish members the app expects but the core does not export: \(missing)")
    #expect(SessionFactory.canFinish)
}
